### ISSUE TITLE
Data Laptop

### ISSUE THREAD

**Issue by yahyarifqi** [yahyarifqi/TopsisLaptop#2]

**Comment by kahfiaulia** [comment]
### ISSUE #2: [MAJOR] Data Laptop
**Tingkat Kesulitan:** Menengah. (Sulit di langkah ke-4. Opsional)
**Estimasi _solving issue_:** 3 hari (7 hari di Tingkat Kesulitan: Sulit. Opsional)
**_Issue Handler_:** Hasda (silakan _assign issue_ secara mandiri)
**Target:** Pengguna dapat melihat Data Laptop seperti yang telah dibuat di Softr sebelumnya. Tetapi pada kali ini, diharapkan (opsional) dapat menampilkan secara lengkap data laptop beserta bobot-bobotnya.

**Instruksi:**
1. Lakukan _fetch_ dan _pull_ terhadap _main branch_ secara rutin, dan _push branch issue_ setiap kali ada perkembangan.
2. Buat halaman Data Laptop.
3. Perhatikan tabel laptop di basis data laptopsis.db. Manfaatkan tabel tersebut untuk menampilkan data.
4. **Opsional:** Lakukan _join table_ dari tabel laptop dengan tabel-tabel relasinya yaitu tabel discrete_criteria dan tabel numeric_criteria. Diharapkan dapat menampilkan mirip dengan Google Spreadsheet PPL (Kelompok 2) di _sheet_ Data Laptop.
5. _Issue_ akan ditutup oleh @yahyarifqi ketika _merging branch issue_ ke _main branch_ berhasil.

**Petunjuk:**
1. Gunakan referensi berikut ini untuk _solving issue_:
https://medium.com/mlearning-ai/how-to-start-learning-sql-with-streamlit-d3edad7494cd
https://python.plainenglish.io/streamlit-and-sqlite-the-ultimate-duo-for-application-development-ccdbc0c25fa2
https://python.plainenglish.io/simple-survey-using-streamlit-sqlite-9dd5d6ec18ad
2. Jika dokumentasi SQLite yang ditemukan masih belum lengkap, maka dapat disesuaikan dengan basis data relasional yang lain seperti MySQL.

**Comment by kahfiaulia** [comment]
### ISSUE #2A: [MAJOR] Update Data Laptop
**Tingkat Kesulitan:** Menengah
**Estimasi _solving issue_:** 3 hari
**_Issue Handler_:** Hasda (silakan _assign issue_ secara mandiri)
**Target:** Pengguna dapat mengubah data laptop. (**OPSIONAL:** Administrator dapat mengubah data laptop.)

**Instruksi:**
1. Lakukan _fetch_ dan _pull_ terhadap _main branch_ secara rutin, dan _push branch issue_ setiap kali ada perkembangan.
2. Perhatikan halaman 1_Data_Laptop.py di folder pages. Ada tabel data laptop yang secara esensinya dibuat dengan menggunakan fungsi `db.get_laptop_data()`.
3. Buat supaya Pengguna bisa mengubah data laptop. Boleh dengan membuat kolom Action dengan tombol 'Ubah' seperti yang sudah pernah dibuat di Softr, atau langsung mengubah _value_ dari _cell_ tabel.
4. OPSIONAL: Adanya _constraint_ supaya hanya Administrator (pengguna yang _logged in_) yang boleh melakukan perubahan data laptop.
5. Tabel dapat diubah atribut-atributnya jika diperlukan. Tetapi jika melakukan perubahan, _migrate/export/backup_ basis data laptopsis.db yang telah dimodifikasi ke _branch issue_.
6. _Issue_ akan ditutup oleh @yahyarifqi ketika _merging branch issue_ ke _main branch_ berhasil.

**Petunjuk:**
1. Data tabel sudah dibuat dengan memanfaatkan pustaka _pandas_ sehingga Anda bisa memanfaatkan fitur-fitur _pandas_ untuk melakukan pengolahan data.
2. Anda bisa memanfaatkan fitur yang telah disediakan oleh Streamlit seperti menggunakan `st.data_editor()` (dokumentasi: https://docs.streamlit.io/library/api-reference/data/st.data_editor) ataupun _component_ yang telah disediakan di https://streamlit.io/components. Dengan menggunakan `st.data_editor()`, Anda dapat melakukan menambah data, perubahan data, menghapus data, mencari data, serta mengunduh data dalam format .csv sekaligus. 
3. Anda tidak diharuskan menggunakan `st.data_editor()`. Anda boleh menggunakan cara apapun untuk _solving issue_ ini.
4. Jika Anda perhatikan dengan detil di halaman 1_Data_Laptop.py, fungsi `init()` mubazir. Untuk saat ini, Anda boleh mengomentari fungsi tersebut dan cukup menggunakan `db.get_laptop_data()` untuk menampilkan data laptop. Sehingga jika Anda hendak menggunakan `st.data_editor()`, Anda boleh menggunakannya seperti contoh berikut: `df = st.data_editor(pd.DataFrame(db.get_laptop_data()), num_rows="dynamic")`
5. Walaupun begitu, Anda dapat memanfaatkan fungsi `init()` semaksimal mungkin untuk melakukan perubahan data yang lebih kuat.
6. Jika Anda ingin membuat _update_ data tabel tanpa menggunakan _pandas_, Anda bisa membuat fungsi baru di dbmanagement.py dengan memanfaatkan statement1 dan statement2 sebagai _query_ dasarnya.
7. Pelajari lebih detil: _"pandas to SQLite", "pandas to SQLite Update Table Data", "SQLite Python", "SQLite Python Update Table Data"_.
8. Jika dokumentasi SQLite yang ditemukan masih belum lengkap, maka dapat disesuaikan dengan basis data relasional yang lain seperti MySQL.
