### ISSUE TITLE
Membuat sistem register dan login

### ISSUE THREAD

**Issue by yahyarifqi** [yahyarifqi/TopsisLaptop#3]

**Comment by kahfiaulia** [comment]
### ISSUE #3: [MAJOR] Membuat sistem register dan login
**Tingkat Kesulitan:** Menengah
**Estimasi _solving issue_:** 3 hari
**_Issue Handler_:** Damarjati (silakan _assign issue_ secara mandiri)
**Target:** Pengguna dapat melakukan register/login. (penggunaan role untuk user untuk saat ini masih opsional).

**Instruksi:**
1. Lakukan _fetch_ dan _pull_ terhadap _main branch_ secara rutin, dan _push branch issue_ setiap kali ada perkembangan.
2. Buat halaman register dan login.
3. Perhatikan tabel user di basis data laptopsis.db. Manfaatkan tabel tersebut untuk melakukan transaksi register/login.
4. Tabel dapat diubah atribut-atributnya jika diperlukan. Tetapi jika melakukan perubahan, _migrate/export/backup_ basis data laptopsis.db yang telah dimodifikasi ke _branch issue_.
5. _Issue_ akan ditutup oleh @yahyarifqi ketika _merging branch issue_ ke _main branch_ berhasil.

**Petunjuk:**
1. Gunakan referensi berikut ini untuk _solving issue_:
https://github.com/blackary/st.database ([database.streamlitapp.com](https://database.streamlitapp.com/))
https://github.com/asehmi/auth-simple-for-streamlit
2. Jika dokumentasi SQLite yang ditemukan masih belum lengkap, maka dapat disesuaikan dengan basis data relasional yang lain seperti MySQL.
